arrowParens: always
bracketSpacing: true
endOfLine: lf
printWidth: 120
semi: true
singleQuote: false
tabWidth: 2
trailingComma: all
overrides:
  - files: "*.sol"
    options:
      printWidth: 120
      tabWidth: 4
      useTabs: false
      singleQuote: false
      bracketSpacing: false

