/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TimeLockedVoteInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "castVote"
      | "createVote"
      | "getEncryptedCounts"
      | "getResults"
      | "getVote"
      | "getVoteCount"
      | "getVoteStatus"
      | "hasUserVoted"
      | "hasVoted"
      | "markAsDecrypted"
      | "protocolId"
      | "requestDecryptionAccess"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DecryptionAccessGranted"
      | "VoteCast"
      | "VoteCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "castVote",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createVote",
    values: [string, string, string[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedCounts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getResults",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVoteStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasUserVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsDecrypted",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDecryptionAccess",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "castVote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedCounts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getResults", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVoteCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoteStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasUserVoted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "markAsDecrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestDecryptionAccess",
    data: BytesLike
  ): Result;
}

export namespace DecryptionAccessGrantedEvent {
  export type InputTuple = [voteId: BigNumberish, requester: AddressLike];
  export type OutputTuple = [voteId: bigint, requester: string];
  export interface OutputObject {
    voteId: bigint;
    requester: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [voteId: BigNumberish, voter: AddressLike];
  export type OutputTuple = [voteId: bigint, voter: string];
  export interface OutputObject {
    voteId: bigint;
    voter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCreatedEvent {
  export type InputTuple = [
    voteId: BigNumberish,
    title: string,
    options: string[],
    deadline: BigNumberish,
    creator: AddressLike
  ];
  export type OutputTuple = [
    voteId: bigint,
    title: string,
    options: string[],
    deadline: bigint,
    creator: string
  ];
  export interface OutputObject {
    voteId: bigint;
    title: string;
    options: string[];
    deadline: bigint;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TimeLockedVote extends BaseContract {
  connect(runner?: ContractRunner | null): TimeLockedVote;
  waitForDeployment(): Promise<this>;

  interface: TimeLockedVoteInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  castVote: TypedContractMethod<
    [
      voteId: BigNumberish,
      encryptedOptionIndex: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createVote: TypedContractMethod<
    [
      title: string,
      description: string,
      options: string[],
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getEncryptedCounts: TypedContractMethod<
    [voteId: BigNumberish],
    [string[]],
    "view"
  >;

  getResults: TypedContractMethod<[voteId: BigNumberish], [bigint[]], "view">;

  getVote: TypedContractMethod<
    [voteId: BigNumberish],
    [
      [string, string, string[], bigint, string, boolean, bigint] & {
        title: string;
        description: string;
        options: string[];
        deadline: bigint;
        creator: string;
        isDecrypted: boolean;
        totalVoters: bigint;
      }
    ],
    "view"
  >;

  getVoteCount: TypedContractMethod<[], [bigint], "view">;

  getVoteStatus: TypedContractMethod<
    [voteId: BigNumberish],
    [
      [boolean, boolean, boolean, bigint] & {
        isActive: boolean;
        isEnded: boolean;
        isDecrypted: boolean;
        timeRemaining: bigint;
      }
    ],
    "view"
  >;

  hasUserVoted: TypedContractMethod<
    [voteId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  markAsDecrypted: TypedContractMethod<
    [voteId: BigNumberish, counts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  requestDecryptionAccess: TypedContractMethod<
    [voteId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "castVote"
  ): TypedContractMethod<
    [
      voteId: BigNumberish,
      encryptedOptionIndex: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createVote"
  ): TypedContractMethod<
    [
      title: string,
      description: string,
      options: string[],
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEncryptedCounts"
  ): TypedContractMethod<[voteId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getResults"
  ): TypedContractMethod<[voteId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [voteId: BigNumberish],
    [
      [string, string, string[], bigint, string, boolean, bigint] & {
        title: string;
        description: string;
        options: string[];
        deadline: bigint;
        creator: string;
        isDecrypted: boolean;
        totalVoters: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoteCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVoteStatus"
  ): TypedContractMethod<
    [voteId: BigNumberish],
    [
      [boolean, boolean, boolean, bigint] & {
        isActive: boolean;
        isEnded: boolean;
        isDecrypted: boolean;
        timeRemaining: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasUserVoted"
  ): TypedContractMethod<
    [voteId: BigNumberish, voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "markAsDecrypted"
  ): TypedContractMethod<
    [voteId: BigNumberish, counts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestDecryptionAccess"
  ): TypedContractMethod<[voteId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "DecryptionAccessGranted"
  ): TypedContractEvent<
    DecryptionAccessGrantedEvent.InputTuple,
    DecryptionAccessGrantedEvent.OutputTuple,
    DecryptionAccessGrantedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoteCreated"
  ): TypedContractEvent<
    VoteCreatedEvent.InputTuple,
    VoteCreatedEvent.OutputTuple,
    VoteCreatedEvent.OutputObject
  >;

  filters: {
    "DecryptionAccessGranted(uint256,address)": TypedContractEvent<
      DecryptionAccessGrantedEvent.InputTuple,
      DecryptionAccessGrantedEvent.OutputTuple,
      DecryptionAccessGrantedEvent.OutputObject
    >;
    DecryptionAccessGranted: TypedContractEvent<
      DecryptionAccessGrantedEvent.InputTuple,
      DecryptionAccessGrantedEvent.OutputTuple,
      DecryptionAccessGrantedEvent.OutputObject
    >;

    "VoteCast(uint256,address)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VoteCreated(uint256,string,string[],uint64,address)": TypedContractEvent<
      VoteCreatedEvent.InputTuple,
      VoteCreatedEvent.OutputTuple,
      VoteCreatedEvent.OutputObject
    >;
    VoteCreated: TypedContractEvent<
      VoteCreatedEvent.InputTuple,
      VoteCreatedEvent.OutputTuple,
      VoteCreatedEvent.OutputObject
    >;
  };
}
